name: 'Publish to NPM'
description: 'Publishes the package to NPM if eligible.'
inputs:
  NPM_TOKEN:
    description: 'NPM authentication token'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub authentication token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check if package can be published
      id: check
      run: |
        if pnpm can-npm-publish; then
          echo "can_publish=true" >> $GITHUB_OUTPUT
        else
          echo "This package cannot be published, as this version already exists."
          echo "can_publish=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Publish Package
      if: steps.check.outputs.can_publish == 'true'
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ inputs.NPM_TOKEN }}" > ~/.npmrc
        pnpm build --verbose
        pnpm publish --access public --no-git-checks
      shell: bash
